export default {
  'master-signup': 'api/user/signup',
  'master-signin': 'api/user/signin',
  'master-province': 'api/province_city/province_user',
  'master-city': 'api/province_city/city_user',
  'master-theme': 'api/theme/user',
  'master-theme-user': 'api/theme/usertheme',
  'master-change-password': 'api/user/changepassword',
  'master-calendar-active': 'api/calendar/user/active',
  'master-user-upload': 'api/user/uploadimage',
  'master-user-update': 'api/user/update',
  'master-self-user': 'api/user/self',
  'master-register-event': 'api/occasion/present',
  'master-point-history': 'api/point/user/history',
  'master-user-tokenfcm': 'api/user/fcm',
  'master-user': 'api/user/user',
  'master-banner': 'api/banner/banner_user',
  'master-bulletin': 'api/bulletin/bulletin_user',
  'master-one-bulletin': 'api/bulletin',
  'master-tree': 'api/tree',
  'master-tree-create': 'api/tree/create'
}
